# Generated by Django 5.1.2 on 2024-10-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_automated',
            field=models.BooleanField(default=False),
        ),
    ]
